services:
  patient-service-db:
    image: postgres:16-alpine
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432" #puerto bd desde mi pc: puerto bd desde el contenedor
    networks:
      - internal
    volumes:
      - "C:/Users/EDWIN GARCIA/Documents/VALENTINA/PERSONAL/Proyectos/Microservicios/db_folder:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5



  auth-service-db:
    image: postgres:16-alpine
    container_name: auth-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5001:5432"
    networks:
      - internal
    volumes:
      - "C:/Users/EDWIN GARCIA/Documents/VALENTINA/PERSONAL/Proyectos/Microservicios/auth_db_folder:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  patient-service:
    #imagen creada con el comando "docker compose up --build -d"
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    container_name: patient-service
    environment:
      #uso de credenciales para acceder al servicio de la bd
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    depends_on:
      patient-service-db:
        condition: service_healthy




  billing-service:
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    container_name: billing-service
    ports:
      - "4001:4001"
      - "9001:9001" #gRPC
    networks:
      - internal



  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal
    depends_on:
      - zookeeper


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - internal




  analytics-service:
    build:
      context: .
      dockerfile: analytics-service/Dockerfile
    container_name: analytics-service
    ports:
      - "4002:4002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal




  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "4004:4004"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:4005
    networks:
      - internal




  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    environment:
      #uso de credenciales para acceder al servicio de la bd
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=mi_clave_secreta_para_prueba_de_autenticacion
    networks:
      - internal
    depends_on:
      auth-service-db:
        condition: service_healthy


networks:
  internal:
    driver: bridge